### DISCUSSION TITLE
Can window corners be set to be rounded?

### DISCUSSION THREAD

**Discussion by sohaha** [wailsapp/wails#2531] [Q&A]
### Describe the solution you'd like

After enabling Frameless, it is no longer possible to achieve window rounded corners effect.

**Comment by airtonix** [comment]
@sohaha Maybe there's something I'm missing but it seems pretty trivial on linux: 

```go

	// Create application with options
	err := wails.Run(&options.App{
		Title:     "myproject",
		Width:     1024,
		Height:    768,
		Frameless: true,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		Windows: &windows.Options{
			WindowIsTranslucent: true, // 👈🏻
		},
		Mac: &mac.Options{
			WindowIsTranslucent: true, // 👈🏻
		},
		Linux: &linux.Options{
			WindowIsTranslucent: true, // 👈🏻
			WebviewGpuPolicy:    linux.WebviewGpuPolicyOnDemand,
		},
		BackgroundColour: &options.RGBA{R: 0, G: 0, B: 0, A: 0},  // 👈🏻
		OnStartup:        app.startup,
		Bind: []interface{}{
			app,
		},
	})
```

`frontend/src/style.css`
```css
html, body {
    margin: 0;
    font-family: "Nunito", -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto",
    "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
}

@font-face {
    font-family: "Nunito";
    font-style: normal;
    font-weight: 400;
    src: local(""),
    url("assets/fonts/nunito-v16-latin-regular.woff2") format("woff2");
}

#app {
    display: grid;
    grid-template-columns: 1fr;
    place-items: center;
    width: 100vw;
    height: 100vh;
    overflow: scroll;
    background-color: white;
    color: black;
    border-radius: 10px;
}
```

![image](https://user-images.githubusercontent.com/61225/232628475-5b7d74d9-e9a6-4c8f-bbf7-7e3b3e27829b.png)
