### DISCUSSION TITLE
Can anyone help me? action Why can't I install the wails CLI?

### DISCUSSION THREAD

**Discussion by lete114** [wailsapp/wails#2770] [Q&A]
![image](https://github.com/wailsapp/wails/assets/48512251/0458ae58-c787-441f-9f8f-e41aacd97fdd)

```yml
name: Wails build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          
      - run: go version
        shell: bash
        
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails
        shell: bash
        
      - name: Install Linux Wails deps
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config
        shell: bash
        
      - name: Install macOS Wails deps
        if: runner.os == 'macOS'
        run: brew install mitchellh/gon/gon
        shell: bash
          
      - name: Build macOS App
        if: runner.os == 'macOS'
        run: wails build --platform darwin/universal
        shell: bash
        
      - name: Build Linux App
        if: runner.os == 'Linux'
        run: wails build --platform linux/amd64,linux/arm64
        shell: bash
        
      - name: Build Windows App
        if: runner.os == 'Windows'
        run: wails build --platform windows/amd64,windows/arm64
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix.os }}
          path: release/
          retention-days: 5
```
