### DISCUSSION TITLE
Build dependencies for different distribution

### DISCUSSION THREAD

**Discussion by jidckii** [wailsapp/wails#4335] [General]
I’ve created a table but couldn’t find the proper way to contribute it to the documentation, so I’ll leave it here.

<hr>

<h3>Build Dependencies for Different Distributions</h3>

Distribution | GTK3 | WebKit2GTK | ABI | Example Installation
-- | -- | -- | -- | --
Debian 12 / Ubuntu 22.04 (and newer) | libgtk-3-0 | libwebkit2gtk-4.1-0 | 4.1 | apt install libgtk-3-0 libwebkit2gtk-4.1-0
Debian 11 / Ubuntu 20.04 (and older) | libgtk-3-0 | libwebkit2gtk-4.0-37 | 4.0 | apt install libgtk-3-0 libwebkit2gtk-4.0-37
openSUSE Leap / Tumbleweed | libgtk-3-0 | libwebkit2gtk-4_1-0 | 4.1 | zypper install libgtk-3-0 libwebkit2gtk-4_1-0
RHEL / CentOS / AlmaLinux / Rocky (up to 9) | gtk3 | webkit2gtk3 | 4.0 | dnf install gtk3 webkit2gtk3
Fedora 40+ | gtk3 | webkit2gtk4.1 | 4.1 | dnf install gtk3 webkit2gtk4.1
Arch Linux / Manjaro | gtk3 | webkit2gtk-4.1 | 4.1 | pacman -S gtk3 webkit2gtk-4.1

<h3>Notes:</h3>
<ul>
<li>
<p>openSUSE Leap provides both WebKitGTK 4.0 and 4.1, but we use <code inline="">libwebkit2gtk-4_1-0</code>.</p>
</li>
<li>
<p>Fedora had only <code inline="">webkit2gtk4.0</code> up to version 39; starting from Fedora 40, <code inline="">webkit2gtk4.1</code> is available.</p>
</li>
<li>
<p>On RHEL / AlmaLinux / Rocky / CentOS (8 and 9), <code inline="">webkit2gtk3</code> corresponds to <strong>ABI 4.0</strong>; 4.1 is not yet available.</p>
</li>
<li>
<p>Arch Linux offers both <code inline="">webkit2gtk</code> and <code inline="">webkit2gtk-4.1</code>, but for the new ABI we use the latter.</p>
</li>
</ul>
<h3>Build Tags:</h3>
<p>As a result, use the <code inline="">-tags webkit2_40</code> build tag <strong>only</strong> for RHEL-based systems.<br>
All other distributions already support the modern version, so use <code inline="">-tags webkit2_41</code> for them.</p>
<hr>
<p><strong>This table reflects the current state of repositories and packages as of May 2025.</strong></p></body></html>

<hr>

##### For RHEL and older other
```yaml
# RHEL/CentOS/AlmaLinux/Rocky Linux 8/9
depends:
  - gtk3
  - webkit2gtk3
overrides:
  # Debian 11 / Ubuntu 20.04 (and older)
  deb:
    depends:
      - libgtk-3-0
      - libwebkit2gtk-4.0-37
  archlinux:
    depends:
      - gtk3
      - webkit2gtk

```

##### For Debian 12 / Ubuntu 22.04 (and newer)  , SUSE , Arch Linux :
```yaml
# Debian 12/Ubuntu 22.04 (and newer)  / SUSE / Arch Linux :
depends:
  - libgtk-3-0
  - libwebkit2gtk-4.1-0
overrides:
  # SUSE
  rpm:
    depends:
      - libgtk-3-0
      - libwebkit2gtk-4_1-0
  archlinux:
    depends:
      - gtk3
      - webkit2gtk-4.1
```

##### For Fedora 40+
```yaml
depends:
  - gtk3
  - webkit2gtk4.1
```

Summary, your need 3 different files for different distro
```sh
$ tree build/linux/nfpm/                                                                                                                                                 
build/linux/nfpm/
├── nfpm_40-rhel-amd64.yaml
├── nfpm_40-rhel-arm64.yaml
├── nfpm_40-rhel.yaml.tpl
├── nfpm_41-deb_suse_arch-amd64.yaml
├── nfpm_41-deb_suse_arch-arm64.yaml
├── nfpm_41-deb_suse_arch.yaml.tpl
├── nfpm_41-fedora-amd64.yaml
├── nfpm_41-fedora-arm64.yaml
├── nfpm_41-fedora.yaml.tpl
```
