### DISCUSSION TITLE
Trying to build a flatpak with a wails.app build

### DISCUSSION THREAD

**Discussion by loloof64** [wailsapp/wails#779] [Q&A] [answered]
I tried to generate and run a flatpak locally with this manifest, but I get an exception when testing the flatpak.
As a side note, the program is just a new project built from Vue3 template.

Manifest 

```
app-id: com.loloof64.HelloWailsVue
runtime: org.gnome.Platform
runtime-version: '3.26'
sdk: org.gnome.Sdk
command: HelloWails
modules:
  - name: HelloWails
    buildsystem: simple
    build-commands:
      - install -D HelloWails /app/bin/HelloWails
    sources:
      - type: file
        path: HelloWails

```

Terminal's stacktrace
```
$> flatpak-builder --run build-dir com.loloof64.HelloWailsVue.yml HelloWails                                                                                                           

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/laurent/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x76b209]

runtime stack:
runtime.throw(0x839200, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x76b1f0, 0xc000115b68, 0xbcc060)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000115b38 sp=0xc000115b00 pc=0x40823b
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewDispatch(0x0, 0x0)
	_cgo_gotypes.go:128 +0x3c fp=0xc000115b68 sp=0xc000115b38 pc=0x7614dc
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Dispatch.func1(0xc0000a8108)
	/usr/local/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/lib/renderer/webview/webview.go:319 +0x6b fp=0xc000115ba8 sp=0xc000115b68 pc=0x762fcb
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Dispatch(0xc0000a8108, 0xc0000cca60)
	/usr/local/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/lib/renderer/webview/webview.go:319 +0xe5 fp=0xc000115bd8 sp=0xc000115ba8 pc=0x7623a5
github.com/wailsapp/wails/lib/renderer.(*WebView).SetColour(0xc0001d0460, 0x823aff, 0x7, 0x13a, 0x400)
	/usr/local/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/lib/renderer/webview.go:136 +0xdd fp=0xc000115c28 sp=0xc000115bd8 pc=0x7645dd
github.com/wailsapp/wails/lib/renderer.(*WebView).Initialise(0xc0001d0460, 0x9193e0, 0xc0001e0000, 0x916530, 0xc0000aaa20, 0x9181e8, 0xc0000c6820, 0x4122fb, 0xc0000999a0)
	/usr/local/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/lib/renderer/webview.go:118 +0x5d7 fp=0xc000115d38 sp=0xc000115c28 pc=0x764337
github.com/wailsapp/wails.(*App).start(0xc00010a780, 0x0, 0x0)
	/usr/local/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/app.go:114 +0x19c fp=0xc000115e50 sp=0xc000115d38 pc=0x768d1c
github.com/wailsapp/wails.(*App).Run(0xc00010a780, 0x79ba60, 0x8b7ea8)
	/usr/local/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/app.go:93 +0xa9 fp=0xc000115eb8 sp=0xc000115e50 pc=0x768a69
main.main()
	/home/laurent/Documents/Programmation/ProjetsPersos/GoLang/HelloWailsVue/main.go:29 +0x136 fp=0xc000115f88 sp=0xc000115eb8 pc=0x76a556
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000115fe0 sp=0xc000115f88 pc=0x43d4f6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000115fe8 sp=0xc000115fe0 pc=0x470e21

```

Here a zip file with the compiled program and the flatpak manifest.
[HelloWails_program_manifest.zip](https://github.com/wailsapp/wails/files/7001087/HelloWails_program_manifest.zip)

**Comment by leaanthony** [comment]
I would *really* like to get this working but am not familiar with flatpak at all. Does it need the shared libraries in the pak file?

**Reply by loloof64** [reply]
I must admit that me neither. I just read the short tutorial from the flatpak page, and changed the FreeDesktop Runtime by the Gnome one. But apart from this, I don't know how to improve my experiment.

The Gnome runtime includes some libraries from FreeDesktop - dbus, pulseaudio, glib, x11, wayland - and add some from Gnome : whose WebkitGTK. But it seems that no GTK is shipped (not in the list). So I bet that GTK shared libraries must be given in the Flatpak.

**Comment by ianmjones** [comment, marked as answer]
@loloof64 I believe you're just missing `finish-args` in the Flatpak manifest.

Every Flatpak manifest must specify what permissions it needs, and for X11/Wayland desktop apps you need a bare minimum of ...

```yaml
finish-args:
  # Window Manager
  - '--share=ipc'
  - '--socket=fallback-x11'
  - '--socket=wayland'
```

Just add that after the `command` entry and you should be good to go.

I created a `wails-flatpak` test repo at https://github.com/ianmjones/wails-flatpak, and progressed it from including a local binary to building it too. I did this as two parts of my [Always Developing](https://www.youtube.com/channel/UCYODqIPqlBv5jRgsRaV0qJQ) YouTube channel. As I write this, the second part (session 56) that actually solves your problem isn't up on YouTube yet, but should be in a day or so.

In my case I also needed to add the `device=dri` permission as I'm using a Nvidia card and it seems the rendering wasn't working without it, so it's probably safest to add that too.

I also used a more recent SDK version, v3.38 rather than v3.26.

Long story short, try this while using your local binary as input...

```yaml
app-id: com.loloof64.HelloWailsVue
runtime: org.gnome.Platform
runtime-version: '3.38'
sdk: org.gnome.Sdk
command: HelloWails
finish-args:
  # Window Manager
  - '--share=ipc'
  - '--socket=fallback-x11'
  - '--socket=wayland'
  - '--device=dri'
modules:
  - name: HelloWails
    buildsystem: simple
    build-commands:
      - install -D HelloWails /app/bin/HelloWails
    sources:
      - type: file
        path: HelloWails
```

My manifest that builds the binary too is at https://github.com/ianmjones/wails-flatpak/blob/main/com.ianmjones.wails-flatpak.yml

However, I had problems with getting `go build` to download the module dependencies, and from looking around I see that other manifests on FlatHub are explicitly downloading theirs to `vendor` as part of their `sources`. There's quite a few dependencies for a Wails desktop app, so I went the route of using `go mod vendor` to save off the dependencies and include them in the repo. Seems to work. :shrug: 

Have fun!

**Reply by leaanthony** [reply]
This is amazing! Thanks @ianmjones! Is there something in Wails we could do to make the module download less painful? I'm looking at doing the heavy lifting as much as possible for generating flatpaks. Cheers.

**Reply by ianmjones** [reply]
> This is amazing! Thanks @ianmjones!

You're welcome, really like what you've done with Wails, least I could do!

> Is there something in Wails we could do to make the module download less painful? I'm looking at doing the heavy lifting as much as possible for generating flatpaks. Cheers.

Hmm, honestly don't know. I'm not that familiar with Flatpak myself, or Go, just know enough to be dangerous. :smile:

**Reply by loloof64** [reply]
Thank you very much @ianmjones 😃 
All is clear for me now 😃

**Reply by leaanthony** [reply]
> Hmm, honestly don't know. I'm not that familiar with Flatpak myself, or Go, just know enough to be dangerous. 😄

You'll fit right in! 😂 Also, great job on the videos. I really like the pace and approach.

**Reply by ianmjones** [reply]
> Also, great job on the videos. I really like the pace and approach.

Thanks, much appreciated!

I realized that I made a mistake in my second video, building from source was broken as I was still relying on the JS/CSS artefacts from a local build, and the dependencies for them aren't going to play well with flatpack-builder's restrictions on build tools. So Part 3 was born!

https://youtu.be/N6lvl4ePCYI

TL;DW (tool long, didn't watch :wink:): Because Wails produces a nice simple executable, there's really no need for building from source in flatpak-builder, you can just grab a release binary from GitHub Releases or another downloads area and bundle it.

The [wails-flatpak repo](https://github.com/ianmjones/wails-flatpak) has been updated as appropriate.

**Reply by leaanthony** [reply]
That's fantastic! For compiling, the binary will be fine. For generating projects, it would be slightly trickier but that sounds like it's not needed.

Are you on slack? I think there would be a lot of support for Flatpak natively in Wails so would love to ask a couple of questions offline on how to achieve that.

Keep up the great work!

**Reply by ianmjones** [reply]
@leaanthony I'll ping you on the Gophers slack. :smile:

**Reply by esimkowitz** [reply]
@leaanthony Checking in, did you end up mainlining support for flatpak? I am not seeing it referenced in the Linux distro documentation: https://wails.io/docs/guides/linux-distro-support

**Reply by leaanthony** [reply]
I spoke with @ianmjones about this a while back and I believe his take was that it was quite difficult regarding getting the permissions right. Things may have changed though

**Reply by esimkowitz** [reply]
I may try to take a crack at it. Is it possible to pack a renderer directly in the binary? That may help with reducing variables.

**Reply by leaanthony** [reply]
I'm not sure bundling WebKit2gtk in the main binary will help you. I think appimage runs something like `ldd` on the binary and copies everything in.

**Reply by ianmjones** [reply]
After the repo discussed here, I created a slightly more up to date version that packages a Wails v1 app as either flatpak, snap, or tgz.

https://github.com/ianmjones/wails-test

At some point I should update it to package a Wails v2 app, but it might be helpful anyway, the Makefile might give you some ideas.

**Comment by robrotheram** [comment]
I thought I will follow up on my own experiments. I have very little experience with building flatpaks but I have gotten a build to work using the latest Wails `Wails CLI v2.7.1`

Mainly by basing my work off [Cinny](https://github.com/flathub/in.cinny.Cinny/blob/master/in.cinny.Cinny.yml) and the work of @ianmjones 

My current WIP manifest looks like this. I am not sure if its the correct approach and it takes ages to build the first time as you are building webkit from source.  But it works for me. 

In the future it would be nice that the steps are in a base runtime that we can use in the same way as you can for electron apps. 
 
```
app-id: io.exceptionerror.gogallery
runtime: org.gnome.Platform
runtime-version: '44'
sdk: org.gnome.Sdk
command: gogallery
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --share=ipc
  - --share=network
  - --filesystem=home
modules:
  - shared-modules/libappindicator/libappindicator-gtk3-12.10.json
  - name: webkit2gtk-4.0
    sources:
      - type: archive
        url: https://webkitgtk.org/releases/webkitgtk-2.42.1.tar.xz
        sha256: 6f41fac9989d3ee51c08c48de1d439cdeddecbc757e34b6180987d99b16d2499
        x-checker-data:
          type: html
          url: https://webkitgtk.org/releases/
          version-pattern: LATEST-STABLE-(\d[\.\d]+\d)
          url-template: https://webkitgtk.org/releases/webkitgtk-$version.tar.xz
    buildsystem: cmake-ninja
    config-opts:
      - -DPORT=GTK
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DENABLE_DOCUMENTATION=OFF
      - -DENABLE_MINIBROWSER=OFF
      - -DENABLE_WEBDRIVER=OFF
      - -DENABLE_GAMEPAD=OFF
      - -DUSE_SOUP2=ON
      - -DENABLE_BUBBLEWRAP_SANDBOX=OFF

    modules:
      - shared-modules/libsoup/libsoup-2.4.json
      - name: unifdef
        no-autogen: true
        make-install-args:
          - prefix=${FLATPAK_DEST}
        sources:
          - type: archive
            url: https://dotat.at/prog/unifdef/unifdef-2.12.tar.xz
            sha256: 43ce0f02ecdcdc723b2475575563ddb192e988c886d368260bc0a63aee3ac400
        cleanup:
          - '*'
      - name: libjxl
        buildsystem: cmake
        config-opts:
          - -DCMAKE_BUILD_TYPE=Release
          - -DBUILD_TESTING=OFF
        sources:
          - type: git
            url: https://github.com/libjxl/libjxl.git
            tag: v0.8.2
            commit: 954b460768c08a147abf47689ad69b0e7beff65e
            disable-shallow-clone: true
            x-checker-data:
              type: git
              tag-pattern: ^v([\d.]+)$
  - name: wails-test
    #
    # Just install the binary from the local filesystem.
    #
    sources:
      - type: dir
        path: .
    buildsystem: simple
    build-commands:
      - install -D build/bin/gogallery /app/bin/gogallery
```
You will also need to add the flathub shared module 
`git submodule add https://github.com/flathub/shared-modules.git`
Then you can build it with the following commands
```
flatpak-builder build-dir io.exceptionerror.gogallery.yml --install --force-clean --user 
flatpak run io.exceptionerror.gogallery
```

**Reply by leaanthony** [reply]
Thanks for sharing this!!

**Comment by ad-on-is** [comment]
For anyone interersted, here's my workflow, **without building webkit**

## Step 1: Build flatpak and extract binary

### Build the Flatpak using GitHub actions
**Action**
https://github.com/ad-on-is/resticity/blob/main/.github/workflows/flatpak.yml

**Flatpak manifest** uses Gnome 3.38
https://github.com/ad-on-is/resticity/blob/main/packaging/flatpak/io.github.ad_on_is.Resticity.yml

Add the produced binary to the release, or somewhere else where you have access to it. We will use it later when publishing to Flathub.

```yaml
- name: "Add to release"
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          Resticity.flatpak # add bundle
          /__w/resticity/resticity/flatpak_app/files/bin/resticity # add binary
```

## Step 2: Publish to Flathub

**Flatpak manifest** uses Gnome 3.38
https://github.com/ad-on-is/flathub/blob/resticity/io.github.ad_on_is.Resticity.yml
