### ISSUE TITLE
MacOS: wails build -o outputName ignored.

### ISSUE THREAD

**Issue by Snider** [wailsapp/wails#2290]
### Description

When building an application on MacOS the -o arg is ignored, and the configuration value in the code is used.

### To Reproduce

```yaml
macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          repository: letheanVPN/desktop
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: letheanTest
          build-platform: darwin/universal
          wails-build-webview2: "embed"
          wails-version: "v2.3.1"
          go-version: ^1.18
          sign: "false"
 ```

### Expected behaviour

The output name to be the same as provided with -o

### Screenshots

<img width="992" alt="image" src="https://user-images.githubusercontent.com/631881/211657355-a868deff-18d0-49f1-a769-25c75674dba5.png">

### System Details

```shell
https://github.com/dAppServer/wails-build-action/actions/runs/3885309312/jobs/6629024935
```

### Additional context

linux and windows will use the -o value; not sure if you build from Linux for macOS if it builds fine or not.

https://github.com/dAppServer/wails-build-action/actions/runs/3885309312
Workflow file to test the GHA: https://github.com/dAppServer/wails-build-action/blob/11-action-fails-with-wails-231-on-macos-due-to-ditto-error/.github/workflows/lethean-desktop.yml

Workflow file to test using GHA: https://github.com/dAppServer/wails-build-action/blob/main/.github/workflows/lethean-desktop.yml
