### ISSUE TITLE
Windows: libstdc++-6.dll was not found

### ISSUE THREAD

**Issue by rolznz** [wailsapp/wails#3532]
### Description

When I do a build of the Wails app from my local Windows computer, my teammate can run it without issue. But when they download the Wails build built from a github action, they get:

"The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem."

I can run the Wails build locally fine, but I suspect because of my development setup I have this library available.

### To Reproduce

1. Create a github action with the following content:
```
name: Wails build - all platforms

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [{ name: example, platform: windows/amd64, os: windows-2019 }]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup GoLang
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: 1.21

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.7.1
        shell: bash

      - name: Wails Doctor
        working-directory: .
        run: wails doctor
        shell: bash

      - name: Build Windows App
        if: runner.os == 'Windows'
        run: wails build --platform windows/amd64 -webview2 download -o ${{ matrix.build.name }}.exe -tags "wails"
        shell: bash

      - uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: example-${{runner.os}}
          path: |
            *\bin\*
          if-no-files-found: error

```
2. Download the built artifact on a normal Windows computer without any dev tooling
3. Unzip and run the built application

### Expected behaviour

Any required files are statically linked, user can start application without issue.

### Screenshots

![image](https://github.com/wailsapp/wails/assets/33993199/e5093c94-425a-40c5-81a0-4709737d3efb)

### Attempted Fixes

Tried to update to the latest version of Wails (2.8.2), tried to use a later version of Windows in the github action (2022), tried to include the files statically through the ldflags argument.

### System Details

```shell
SUCCESS  Scanning system - Please wait (this may take a long time)...
                                                                                
# Wails
Version | v2.7.1

# System
┌──────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows Server 2019 Datacenter                                |
| Version      | 1809 (Build: 17763)                                           |
| ID           |                                                               |
| Go Version   | go1.21.11                                                     |
| Platform     | windows                                                       |
| Architecture | amd64                                                         |
| CPU          | AMD EPYC 7763 64-Core Processor                               |
| GPU          | Microsoft Hyper-V Video (Microsoft) - Driver: 10.0.17763.2145 |
| Memory       | 16GB                                                          |
└──────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version |
| WebView2   | N/A          | Available |         |
| Nodejs     | N/A          | Installed | 20.14.0 |
| npm        | N/A          | Installed | 10.7.0  |
| *upx       | N/A          | Available |         |
| *nsis      | N/A          | Installed | v3.10   |
└──────────── * - Optional Dependency ────────────┘
```
