### ISSUE TITLE
[v3] wails3 alpha 8 schema changes not working

### ISSUE THREAD

**Issue by gtsteffaniak** [wailsapp/wails#3935]
### Description

using wails3 alpha 8 , I noticed my current app requires several schema and build changes. 

Perhaps there should be a migration guide for the alpha 8 coming from alpha 7. However, even creating the basic app template results in some errors:

```
2024/12/06 08:26:42 INFO Changing Working Directory dir=[removed]/myfirstapp
2024/12/06 08:26:42 INFO Refresh Starting...
  ERROR   task: Invalid schema version in Taskfile "[removed]/myfirstapp/Taskfile.yml":
          Schema version (3.0.0) is greater than the current version of Task (3.0.0-alpha.8)
2024/12/06 08:26:42 ERROR Running Command exec="wails3 task common:install:frontend:deps" err="exit status 1"
```

### To Reproduce

```
go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest
```
Then init with wails 3 alpha 8
```
wails3 init -n myfirstapp
Creating project
----------------

Project Name      | myfirstapp                                    
Project Directory | [removed]/myfirstapp
Template          | Vanilla + Vite                                
Template Source   | https://wails.io                              

Project 'myfirstapp' created successfully.
```
try to run wails3 dev inside project:

```
2024/12/06 08:26:42 INFO Changing Working Directory dir=[removed]/myfirstapp
2024/12/06 08:26:42 INFO Refresh Starting...
  ERROR   task: Invalid schema version in Taskfile "[removed]/myfirstapp/Taskfile.yml":
          Schema version (3.0.0) is greater than the current version of Task (3.0.0-alpha.8)
2024/12/06 08:26:42 ERROR Running Command exec="wails3 task common:install:frontend:deps" err="exit status 1"
```

### Expected behaviour

Either a warning that the project structure doesn't match wails3 alpha 8 with help on migrating, or a fix.

### System Details

```shell
# System
┌──────────────────────────────────────────────────┐
| Name          | MacOS                            |
| Version       | 14.4.1                           |
| ID            | 23E224                           |
| Branding      | Sonoma                           |
| Platform      | darwin                           |
| Architecture  | arm64                            |
| Apple Silicon | true                             |
| CPU           | Apple M1 Pro                     |
| CPU 1         | Apple M1 Pro                     |
| CPU 2         | Apple M1 Pro                     |
| GPU           | 16 cores, Metal Support: Metal 3 |
| Memory        | 32 GB                            |
└──────────────────────────────────────────────────┘

# Build Environment
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Wails CLI      | v3.0.0-alpha.8                                                                                                            |
| Go Version     | go1.23.1                                                                                                                  |
| -buildmode     | exe                                                                                                                       |
| -compiler      | gc                                                                                                                        |
| CGO_CFLAGS     |                                                                                                                           |
| CGO_CPPFLAGS   |                                                                                                                           |
| CGO_CXXFLAGS   |                                                                                                                           |
| CGO_ENABLED    | 1                                                                                                                         |
| CGO_LDFLAGS    |                                                                                                                           |
| DefaultGODEBUG | asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1 |
| GOARCH         | arm64                                                                                                                     |
| GOARM64        | v8.0                                                                                                                      |
| GOOS           | darwin                                                                                                                    |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by NectoT** [comment]
I was trying to migrate my project from v2 to the latest alpha and encountered the same problem.

This isn't a real fix, but I managed to circumvent the issue by using a standalone [`task`](https://taskfile.dev/installation/#npm) cli, instead of the built in `wails3 task`, and use `build` and `dev` tasks. I also had to make changes to `config.yaml` and replace all calls to `wails3 task` to make `task dev` work:

<details><summary>Details</summary>
<p>

```yaml
# Dev mode configuration
dev_mode:
  root_path: .
  log_level: warn
  debounce: 1000
  ignore:
    dir:
      - .git
      - node_modules
      - frontend
      - bin
    file:
      - .DS_Store
      - .gitignore
      - .gitkeep
    watched_extension:
      - "*.go"
    git_ignore: true
  executes:
    - cmd: task common:install:frontend:deps  # instead of `wails3 task common:install:frontend:deps`
      type: once
    - cmd: task common:dev:frontend  # instead of `wails3 task common:dev:frontend`
      type: background
    - cmd: go mod tidy
      type: blocking
    - cmd: task build  # instead of `wails3 task build`
      type: blocking
    - cmd: task run  # instead of `wails3 task run`
      type: primary
```

</p>
</details>
