### ISSUE TITLE
Wails v2.10.0 use "darwin/universal" platform raise go error

### ISSUE THREAD

**Issue by aotoki-qiu-ggl** [wailsapp/wails#4084]
### Description

After upgrading to `v2.10.0` the `darwin/universal` platform will raise `go: unsupported GOOS/GOARCH pair darwin/universal` error.

### To Reproduce

1. Upgrade to `v2.10.0` with `go mod vendor`
2. Update GitHub Action
  * `go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.0`
  * `go install mvdan.cc/garble@latest`
3. Run GitHub Action and an error is raised

### Expected behaviour

The `wails build` command works correctly.

### System Details

```shell
* GitHub Action OS `macos-latest` or `macos-13`
* Golang Version `1.23.5`
* Platform `darwin/amd64` or `darwin/arm64`

> Both ARM and Intel macOS are tested and have the same issue.
```

```shell
# Wails
Version | v2.10.0
# System
┌───────────────────────────────────┐
| OS           | MacOS              |
| Version      | 14.7.2             |
| ID           | 23H311             |
| Go Version   | go1.23.4           |
| Platform     | darwin             |
| Architecture | arm64              |
| CPU          | Apple M1 (Virtual) |
| GPU          | Unknown            |
| Memory       | 7GB                |
└───────────────────────────────────┘
# Dependencies
┌────────────────────────────────────────────────────
| Dependency                | Package Name | Status    | Version       |
| Xcode command line tools  | N/A          | Installed | 2[40](https://github.com/***/common-desktop/actions/runs/13364796883/job/37320361251#step:8:41)8          |
| Nodejs                    | N/A          | Installed | 20.9.0        |
| npm                       | N/A          | Installed | 10.1.0        |
| *Xcode                    | N/A          | Installed | 15.4 (15F31d) |
| *upx                      | N/A          | Available |               |
| *nsis                     | N/A          | Available |               |
└────────────────────── * - Optional Dependency ───────────────────────┘
# Diagnosis
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
 SUCCESS  Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by meeehdi-dev** [comment]
Hi,

I also had the issue with `darwin/universal` but it seems ok when using `darwin/amd64` (https://github.com/meeehdi-dev/dbisous/actions/runs/13380920892/job/37369240194) and `darwin/arm64` (https://github.com/meeehdi-dev/dbisous/actions/runs/13380996363/job/37369433710)
the only difference is that I use go 1.24 instead of 1.23.5 in your case.

**Comment by Snider** [comment]
It affects 13, 14 and 15 on 2.10.0

https://github.com/dAppServer/wails-build-action/actions/runs/13430986943/job/37522638331

Temp fix, I got the action test rebuilding, dropping the Wails version on macros ` wails-version: "v2.9.0"`

if anyone has a fix i'll port it over to the gha :)

```
  macos-obfuscate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: darwin/universal
          build-obfuscate: true
          wails-version: "v2.9.0"
          package: false # Do not try to upload to github
```
https://github.com/dAppServer/wails-build-action/actions/runs/13431358782/job/37523774667#step:3:6
