### ISSUE TITLE
[v3] Build dependencies for different distribution

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#4339]
Look to double check nfpm config in v3 + doctor.

-----

### Discussed in https://github.com/wailsapp/wails/discussions/4335

<div type='discussions-op-text'>

<sup>Originally posted by **jidckii** June  5, 2025</sup>
I’ve created a table but couldn’t find the proper way to contribute it to the documentation, so I’ll leave it here.

<hr>

<h3>Build Dependencies for Different Distributions</h3>

Distribution | GTK3 | WebKit2GTK | ABI | Example Installation
-- | -- | -- | -- | --
Debian 12 / Ubuntu 22.04 (and newer) | libgtk-3-0 | libwebkit2gtk-4.1-0 | 4.1 | apt install libgtk-3-0 libwebkit2gtk-4.1-0
Debian 11 / Ubuntu 20.04 (and older) | libgtk-3-0 | libwebkit2gtk-4.0-37 | 4.0 | apt install libgtk-3-0 libwebkit2gtk-4.0-37
openSUSE Leap / Tumbleweed | libgtk-3-0 | libwebkit2gtk-4_1-0 | 4.1 | zypper install libgtk-3-0 libwebkit2gtk-4_1-0
RHEL / CentOS / AlmaLinux / Rocky (up to 9) | gtk3 | webkit2gtk3 | 4.0 | dnf install gtk3 webkit2gtk3
Fedora 40+ | gtk3 | webkit2gtk4.1 | 4.1 | dnf install gtk3 webkit2gtk4.1
Arch Linux / Manjaro | gtk3 | webkit2gtk-4.1 | 4.1 | pacman -S gtk3 webkit2gtk-4.1

<h3>Notes:</h3>
<ul>
<li>
<p>openSUSE Leap provides both WebKitGTK 4.0 and 4.1, but we use <code inline="">libwebkit2gtk-4_1-0</code>.</p>
</li>
<li>
<p>Fedora had only <code inline="">webkit2gtk4.0</code> up to version 39; starting from Fedora 40, <code inline="">webkit2gtk4.1</code> is available.</p>
</li>
<li>
<p>On RHEL / AlmaLinux / Rocky / CentOS (8 and 9), <code inline="">webkit2gtk3</code> corresponds to <strong>ABI 4.0</strong>; 4.1 is not yet available.</p>
</li>
<li>
<p>Arch Linux offers both <code inline="">webkit2gtk</code> and <code inline="">webkit2gtk-4.1</code>, but for the new ABI we use the latter.</p>
</li>
</ul>
<h3>Build Tags:</h3>
<p>As a result, use the <code inline="">-tags webkit2_40</code> build tag <strong>only</strong> for RHEL-based systems.<br>
All other distributions already support the modern version, so use <code inline="">-tags webkit2_41</code> for them.</p>
<hr>
<p><strong>This table reflects the current state of repositories and packages as of May 2025.</strong></p></body></html>

<hr>

##### For RHEL and older other
```yaml
# RHEL/CentOS/AlmaLinux/Rocky Linux 8/9
depends:
  - gtk3
  - webkit2gtk3
overrides:
  # Debian 11 / Ubuntu 20.04 (and older)
  deb:
    depends:
      - libgtk-3-0
      - libwebkit2gtk-4.0-37
  archlinux:
    depends:
      - gtk3
      - webkit2gtk

```

##### For Debian 12 / Ubuntu 22.04 (and newer)  , SUSE , Arch Linux :
```yaml
# Debian 12/Ubuntu 22.04 (and newer)  / SUSE / Arch Linux :
depends:
  - libgtk-3-0
  - libwebkit2gtk-4.1-0
overrides:
  # SUSE
  rpm:
    depends:
      - libgtk-3-0
      - libwebkit2gtk-4_1-0
  archlinux:
    depends:
      - gtk3
      - webkit2gtk-4.1
```

##### For Fedora 40+
```yaml
depends:
  - gtk3
  - webkit2gtk4.1
```

Summary, your need 3 different files for different distro
```sh
$ tree build/linux/nfpm/                                                                                                                                                 
build/linux/nfpm/
├── nfpm_40-rhel-amd64.yaml
├── nfpm_40-rhel-arm64.yaml
├── nfpm_40-rhel.yaml.tpl
├── nfpm_41-deb_suse_arch-amd64.yaml
├── nfpm_41-deb_suse_arch-arm64.yaml
├── nfpm_41-deb_suse_arch.yaml.tpl
├── nfpm_41-fedora-amd64.yaml
├── nfpm_41-fedora-arm64.yaml
├── nfpm_41-fedora.yaml.tpl
```</div>

**Comment by leaanthony** [comment]
Added runtime dependencies documentation to the Linux distro support guide in commit 17bce06c5.

The documentation now includes:
- Runtime dependencies table for different distributions (Debian, Ubuntu, Fedora, RHEL, openSUSE, Arch)
- WebKit2GTK ABI version differences (4.0 vs 4.1) and build tags
- nfpm configuration examples for packaging

See: https://wails.io/docs/guides/linux-distro-support#runtime-dependencies

Thanks to @jidckii for the original contribution in the discussion!

**Comment by leaanthony** [comment]
Reopening - the docs commit was reverted. Will create a proper PR instead.

**Comment by leaanthony** [comment]
Created PR #4779 with the runtime dependencies documentation.

Includes:
- Runtime dependencies table for 6 distro families
- WebKit2GTK ABI version explanation (4.0 vs 4.1)  
- Build tag documentation
- nfpm packaging configuration examples

Thanks to @jidckii for the original contribution!

**Comment by jidckii** [comment]
@leaanthony 
Hi, sorry, I didn't see this PR right away and didn't update the information in the discussion.
Recently I learned that in RPM you can use dependencies via the Provides field in the package.
This greatly simplifies creating universal rpm packages.
Debian doesn't have this, but fortunately in the deb world there isn't such fragmentation and packages are named the same everywhere.
So here's the updated information:

## ABI 4.0

```yaml
overrides:
  # Debian 11+ / Ubuntu 20.04+
  deb:
    depends:
      - libgtk-3-0
      - libwebkit2gtk-4.0-37
  # RHEL/CentOS/AlmaLinux/Rocky Linux 8/9
  rpm:
    depends:
      - "libgtk-3.so.0()(64bit)"
      - "libwebkit2gtk-4.0.so.37()(64bit)"
  archlinux:
    depends:
      - gtk3
      - webkit2gtk
```

## ABI 4.1

```yaml
overrides:
  # Debian12+/Ubuntu22.04+
  deb:
    depends:
      - libgtk-3-0
      - libwebkit2gtk-4.1-0
  # RHEL/CentOS/AlmaLinux/Rocky Linux 10+
  rpm:
    depends:
      - "libgtk-3.so.0()(64bit)"
      - "libwebkit2gtk-4.1.so.0()(64bit)"
  archlinux:
    depends:
      - gtk3
      - webkit2gtk-4.1
```
