### ISSUE TITLE
Support to goreleaser

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#747]
Is there a way to use https://github.com/goreleaser/goreleaser/ along with Wails ?
I would like to automate the delivery of my wails app binaries

**Comment by leaanthony** [comment]
Not got much experience with goreleaser but IIRC you have build hooks? I'd wrap your wails build command in a script and run that script from goreleaser.

**Comment by SavageCore** [comment]
If anyone ends up here from searching here's a basic example: 

```
builds:
    ...
    hooks:
      post:
        - wails build ...
        - cp build/bin/app.exe dist/app-go_windows_amd64_v1
```

We build with Wails and then copy the resulting binary to where `goreleaser` expects it, the build will then carry on as usual archiving etc.
